# k8s/secretprovider.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ecomm-keyvault-secrets
  namespace: ecomm-backend
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: $(CSI_CLIENT_ID)
   
    keyvaultName: "${key_vault_name}"  # From your Key Vault name
    objects: |
      array:
        - |
          objectName: JWT-SECRET
          objectType: secret
        - |
          objectName: JWT-EXPIRY
          objectType: secret
        - |
          objectName: VITE-STRIPE-PUBLISHABLE-KEY
          objectType: secret
        - |
          objectName: stripe-secret-key 
          objectType: secret
          objectAlias: STRIPE_SECRET_KEY      
        - |
          objectName: STRIPE-SECRET-KEY
          objectType: secret
        - |
          objectName: STRIPE-WEBHOOK-SECRET
          objectType: secret
        - |
          objectName: REDIS-URL
          objectType: secret
        - |
          objectName: REDIS-HOST
          objectType: secret
        - |
          objectName: REDIS-PORT
          objectType: secret
        - |
          objectName: REDIS-PASSWORD
          objectType: secret
        - |
          objectName: REDIS-SSL
          objectType: secret
        - |
          objectName: postgres-host
          objectType: secret
          objectVersion: ""
        - |
          objectName: postgres-port
          objectType: secret
        - |
          objectName: postgres-user
          objectType: secret
        - |
          objectName: postgres-password
          objectType: secret
    tenantId: $(TENANT_ID)