# k8s/secretprovider.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ecomm-keyvault-secrets
  namespace: ecomm-frontend
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: $(CSI_CLIENT_ID)
    keyvaultName: ${key_vault_name}  # From your Key Vault name
    objects: |
      array:
        - |
          objectName: VITE-API-URL
          objectType: secret
        - |
          objectName: VITE-STRIPE-PUBLISHABLE-KEY
          objectType: secret
    tenantId: $(TENANT_ID)